language = "C"
include_guard = "PUNIYU_LOGGER_H"
autogen_warning = "/* 警告: 此文件由 cbindgen 自动生成，请勿手动修改 */"
header = """
#ifdef _WIN32
  #ifdef PUNIYU_LOGGER_EXPORTS
    #define PUNIYU_LOGGER __declspec(dllexport)
  #else
    #define PUNIYU_LOGGER __declspec(dllimport)
  #endif
#else
  #define PUNIYU_LOGGER
#endif
"""

[export]
include = ["LoggerOptions"]

[fn]
prefix = "PUNIYU_LOGGER"
